apiVersion: admissionregistration.k8s.io/v1
kind: MutatingAdmissionPolicyBinding
metadata:
  name: bind-add-gotham-required-namespace-label
spec:
  policyName: gotham-required-label
  matchResources:
    namespaceSelector:
      matchLabels:
        city: gotham
